[package]
name = "buzz"
version = "0.1.0"
edition = "2021"

[dependencies]
buzz-types = { path = "../buzz-types" }
buzz-codegen = { path = "../buzz-codegen" }
thiserror = "1.0"

[dev-dependencies]
proptest = "1"
