[package]
name = "buzz-codegen"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
buzz-types = { path = "../buzz-types" }
syn = { version = "1.0", features = ["full"] }
quote = "1.0"

