use crate::{HttpMethod, SegmentType};

/// Contains preparsed route segments and the HTTP method that corresponds to a handler.
///
/// This struct is generated by the [`get`](buzz_codegen::get) macro (and similar).
pub struct RouteMetadata {
    pub route: &'static [SegmentType],
    pub method: HttpMethod,
}
