[package]
name = "buzz-types"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
quote = "1.0"
async-trait = "0.1.88"
